title: 肉とお米とブロッコリー
author: makietan
description: ここは日報をメインに書きます.
lang: 'ja'

twitter_username: makietanx
github_username:  makietan
rss: rss

url: https://makietan.github.io

baseurl: ""

markdown: kramdown

kramdown:
  input: GFM
  gfm_emojis: true

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

google_analytics: true
google_adsense: true
bing_webmaster: true

timezone: Asia/Tokyo

future: false

exclude: ["README.md", "CONTRIBUTING.md", ".travis.yml", "Gemfile", "Gemfile.lock", ".updated", "Rakefile", "vendor", "tmp", "lib", "LICENSE", ".textlintrc", "package-lock.json", "package.json", "node_modules", ".vscode"]

show_excerpts: true

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

related_post_count: 5
